### ISSUE TITLE
Do you have linux version for this toolkit?

### ISSUE THREAD

**Issue by iezhanqingran** [nygard/GnuSpeech#1]
Hi,

Noticed that the gnu toolkit  can be complied on os X, do you have the linux version?

Thanks

**Comment by josephbburg** [comment]
Hello. I was looking for the same thing and found that the stand-alone version is what you probably wanted:   https://github.com/mym-br/gnuspeech_sa
It worked for me.

**Comment by iezhanqingran** [comment]
Thanks! I'll try it
